network:
  env: stage

network:
  region: us-east-1

infra:
  ec2:
    web:
      ami_filter: defaultb1_ami_filter
      subnets:
        - defaultb1_subnet1a
        - defaultb1_subnet1b
  versions:
    terraform_version: 1.1.1
    aws_version: 2.2.2


other:
  addr: "default1_url:443"
  database_service:
    enabled: "yes"
    enable_rds: "default1_true"  # Comment
    enable_aurora: true  # Everything is Awesome!
